package com.example.game.content

import androidx.compose.ui.graphics.Color
import com.example.R
import com.example.game.core.AttackType
import com.example.game.core.MoveData
import com.example.game.model.Archetype
import com.example.game.model.CharacterDef
import com.example.game.model.CostumePalette
import com.example.game.model.SpecialMoveDef

object FighterRegistry {

    val KAIRO = CharacterDef(
        id = "kairo",
        name = "Kairo",
        subtitle = "THE RIFTBORN",
        bio = "A quiet martial prodigy who harnesses ancient dimensional rift energy through his bandaged arms. Aggressive, relentless, and lightning-fast.",
        archetype = Archetype.RUSHDOWN,
        fightingStyle = "Close-range rift rushdown",
        primaryColor = Color(0xFFD4F878), // Neon Rift Green
        secondaryColor = Color(0xFF38A169),
        portraitResId = R.drawable.portrait_kairo_1790969300673,
        idleSpriteResId = R.drawable.sprite_kairo_idle_1790970661272,
        attackSpriteResId = R.drawable.sprite_kairo_attack_1790970672507,
        maxHealth = 100f,
        walkSpeed = 360f,
        dashSpeed = 620f,
        jumpVelocity = 740f,
        visualScale = 1.0f,
        lightPunch = MoveData(
            name = "Rift Jab",
            type = AttackType.LIGHT_PUNCH,
            startupFrames = 3,
            activeFrames = 3,
            recoveryFrames = 6,
            damage = 7f,
            meterGain = 8f,
            hitStunFrames = 12,
            blockStunFrames = 8,
            pushback = 30f,
            reach = 140f,
            heightOffset = 135f,
            hitboxHeight = 45f,
            soundKey = "hit_light"
        ),
        heavyPunch = MoveData(
            name = "Iron Breaker",
            type = AttackType.HEAVY_PUNCH,
            startupFrames = 6,
            activeFrames = 4,
            recoveryFrames = 10,
            damage = 14f,
            meterGain = 14f,
            hitStunFrames = 18,
            blockStunFrames = 11,
            pushback = 65f,
            reach = 175f,
            heightOffset = 130f,
            hitboxHeight = 50f,
            soundKey = "hit_heavy"
        ),
        lightKick = MoveData(
            name = "Shin Snap",
            type = AttackType.LIGHT_KICK,
            startupFrames = 4,
            activeFrames = 3,
            recoveryFrames = 7,
            damage = 9f,
            meterGain = 10f,
            hitStunFrames = 14,
            blockStunFrames = 9,
            pushback = 38f,
            reach = 155f,
            heightOffset = 50f,
            hitboxHeight = 40f,
            isLow = true,
            soundKey = "hit_light"
        ),
        heavyKick = MoveData(
            name = "Rising Dragon Heel",
            type = AttackType.HEAVY_KICK,
            startupFrames = 8,
            activeFrames = 5,
            recoveryFrames = 13,
            damage = 18f,
            meterGain = 18f,
            hitStunFrames = 24,
            blockStunFrames = 12,
            pushback = 80f,
            reach = 190f,
            heightOffset = 155f,
            hitboxHeight = 65f,
            isLauncher = true,
            soundKey = "hit_heavy"
        ),
        specialMove = SpecialMoveDef(
            name = "Rift Strike",
            commandHint = "SP (L / Button)",
            description = "Fires a concentrated wave of glowing rift energy across the battlefield. Hits full screen.",
            moveData = MoveData(
                name = "Rift Strike",
                type = AttackType.SPECIAL,
                startupFrames = 9,
                activeFrames = 5,
                recoveryFrames = 14,
                damage = 25f,
                meterGain = 15f,
                hitStunFrames = 26,
                blockStunFrames = 14,
                pushback = 90f,
                reach = 0f, // Projectile
                heightOffset = 130f,
                hitboxHeight = 55f,
                spawnsProjectile = true,
                soundKey = "projectile"
            )
        ),
        superArt = SpecialMoveDef(
            name = "Rift Cataclysm",
            commandHint = "EX / SUPER (100 Meter)",
            description = "Unleashes full dimensional rift power with a multi-hit supersonic combo ending in an explosive energy eruption!",
            moveData = MoveData(
                name = "Rift Cataclysm",
                type = AttackType.SUPER,
                startupFrames = 4,
                activeFrames = 12,
                recoveryFrames = 18,
                damage = 50f,
                meterGain = 0f,
                meterCost = 100f,
                hitStunFrames = 45,
                blockStunFrames = 20,
                pushback = 130f,
                reach = 220f,
                heightOffset = 120f,
                hitboxHeight = 90f,
                isKnockdown = true,
                soundKey = "super_activation"
            )
        ),
        quoteWin = "Even the strongest titans crumble before the rift.",
        quoteLoss = "I need... to focus my spirit."
    )

    val COLOSSUS = CharacterDef(
        id = "colossus",
        name = "The Colossus",
        subtitle = "ANCIENT TITAN",
        bio = "A primordial behemoth forged from black obsidian stone and living subterranean magma. Slow-moving, but possesses catastrophic power and armor.",
        archetype = Archetype.TITAN_POWER,
        fightingStyle = "Heavy-hitting volcanic force",
        primaryColor = Color(0xFFFF5238), // Molten Magma
        secondaryColor = Color(0xFFFF9933),
        portraitResId = R.drawable.portrait_colossus_1790969314110,
        idleSpriteResId = R.drawable.sprite_colossus_idle_1790970684554,
        attackSpriteResId = R.drawable.sprite_colossus_attack_1790970696983,
        maxHealth = 115f,
        walkSpeed = 260f,
        dashSpeed = 440f,
        jumpVelocity = 650f,
        visualScale = 1.25f,
        weight = 1.4f,
        lightPunch = MoveData(
            name = "Basalt Jab",
            type = AttackType.LIGHT_PUNCH,
            startupFrames = 5,
            activeFrames = 4,
            recoveryFrames = 8,
            damage = 10f,
            meterGain = 9f,
            hitStunFrames = 15,
            blockStunFrames = 10,
            pushback = 45f,
            reach = 160f,
            heightOffset = 150f,
            hitboxHeight = 55f,
            soundKey = "hit_heavy"
        ),
        heavyPunch = MoveData(
            name = "Seismic Hammer",
            type = AttackType.HEAVY_PUNCH,
            startupFrames = 10,
            activeFrames = 6,
            recoveryFrames = 16,
            damage = 22f,
            meterGain = 18f,
            hitStunFrames = 26,
            blockStunFrames = 16,
            pushback = 100f,
            reach = 205f,
            heightOffset = 140f,
            hitboxHeight = 70f,
            soundKey = "hit_heavy"
        ),
        lightKick = MoveData(
            name = "Lava Sweep",
            type = AttackType.LIGHT_KICK,
            startupFrames = 6,
            activeFrames = 4,
            recoveryFrames = 9,
            damage = 11f,
            meterGain = 10f,
            hitStunFrames = 16,
            blockStunFrames = 10,
            pushback = 48f,
            reach = 175f,
            heightOffset = 60f,
            hitboxHeight = 45f,
            isLow = true,
            soundKey = "hit_heavy"
        ),
        heavyKick = MoveData(
            name = "Volcanic Stomp",
            type = AttackType.HEAVY_KICK,
            startupFrames = 11,
            activeFrames = 6,
            recoveryFrames = 16,
            damage = 24f,
            meterGain = 20f,
            hitStunFrames = 28,
            blockStunFrames = 17,
            pushback = 115f,
            reach = 210f,
            heightOffset = 130f,
            hitboxHeight = 75f,
            isLauncher = true,
            soundKey = "hit_heavy"
        ),
        specialMove = SpecialMoveDef(
            name = "Magma Surge",
            commandHint = "SP (L / Button)",
            description = "Strikes the ground, projecting an erupting geyser of molten magma ahead.",
            moveData = MoveData(
                name = "Magma Surge",
                type = AttackType.SPECIAL,
                startupFrames = 12,
                activeFrames = 6,
                recoveryFrames = 16,
                damage = 30f,
                meterGain = 16f,
                hitStunFrames = 30,
                blockStunFrames = 18,
                pushback = 110f,
                reach = 0f, // Projectile
                heightOffset = 110f,
                hitboxHeight = 75f,
                spawnsProjectile = true,
                soundKey = "projectile"
            )
        ),
        superArt = SpecialMoveDef(
            name = "Volcanic Cataclysm",
            commandHint = "EX / SUPER (100 Meter)",
            description = "Shatters the ground beneath, erupting an infernal volcanic vortex that incinerates everything in its path!",
            moveData = MoveData(
                name = "Volcanic Cataclysm",
                type = AttackType.SUPER,
                startupFrames = 6,
                activeFrames = 14,
                recoveryFrames = 22,
                damage = 56f,
                meterGain = 0f,
                meterCost = 100f,
                hitStunFrames = 50,
                blockStunFrames = 24,
                pushback = 150f,
                reach = 250f,
                heightOffset = 130f,
                hitboxHeight = 110f,
                isKnockdown = true,
                soundKey = "super_activation"
            )
        ),
        quoteWin = "YOU ARE DUST BEFORE THE EARTH.",
        quoteLoss = "THE STONE... CRACKS..."
    )

    val REN = CharacterDef(
        id = "ren",
        name = "Ren",
        subtitle = "SHADOW SHINOBI",
        bio = "An agile shadow ninja whose movements leave phantom silhouettes. Specializes in rapid lightning-fast multi-hit air juggles and evasive counters.",
        archetype = Archetype.SHINOBI_SPEED,
        fightingStyle = "Shadow lightning assassination",
        primaryColor = Color(0xFFA855F7), // Neon Cyber Purple
        secondaryColor = Color(0xFF60A5FA),
        portraitResId = R.drawable.portrait_ren_1790969326808,
        idleSpriteResId = R.drawable.sprite_ren_idle_1790970707623,
        attackSpriteResId = R.drawable.sprite_ren_idle_1790970707623,
        maxHealth = 92f,
        walkSpeed = 400f,
        dashSpeed = 680f,
        jumpVelocity = 780f,
        visualScale = 0.95f,
        lightPunch = MoveData(
            name = "Shadow Kunai",
            type = AttackType.LIGHT_PUNCH,
            startupFrames = 2,
            activeFrames = 3,
            recoveryFrames = 5,
            damage = 6f,
            meterGain = 7f,
            hitStunFrames = 11,
            blockStunFrames = 7,
            pushback = 25f,
            reach = 145f,
            heightOffset = 130f,
            hitboxHeight = 40f,
            soundKey = "slash"
        ),
        heavyPunch = MoveData(
            name = "Phantom Slash",
            type = AttackType.HEAVY_PUNCH,
            startupFrames = 5,
            activeFrames = 4,
            recoveryFrames = 8,
            damage = 13f,
            meterGain = 12f,
            hitStunFrames = 17,
            blockStunFrames = 10,
            pushback = 55f,
            reach = 170f,
            heightOffset = 125f,
            hitboxHeight = 45f,
            soundKey = "slash"
        ),
        lightKick = MoveData(
            name = "Gale Sweep",
            type = AttackType.LIGHT_KICK,
            startupFrames = 3,
            activeFrames = 3,
            recoveryFrames = 6,
            damage = 8f,
            meterGain = 8f,
            hitStunFrames = 13,
            blockStunFrames = 8,
            pushback = 30f,
            reach = 150f,
            heightOffset = 45f,
            hitboxHeight = 35f,
            isLow = true,
            soundKey = "hit_light"
        ),
        heavyKick = MoveData(
            name = "Moon Vault Kick",
            type = AttackType.HEAVY_KICK,
            startupFrames = 7,
            activeFrames = 5,
            recoveryFrames = 11,
            damage = 16f,
            meterGain = 16f,
            hitStunFrames = 23,
            blockStunFrames = 12,
            pushback = 75f,
            reach = 185f,
            heightOffset = 160f,
            hitboxHeight = 60f,
            isLauncher = true,
            soundKey = "hit_heavy"
        ),
        specialMove = SpecialMoveDef(
            name = "Shadow Shuriken Flurry",
            commandHint = "SP (L / Button)",
            description = "Fires a rapid triple volley of lightning-infused shadow shurikens that pierce through the air.",
            moveData = MoveData(
                name = "Shadow Shuriken Flurry",
                type = AttackType.SPECIAL,
                startupFrames = 7,
                activeFrames = 5,
                recoveryFrames = 12,
                damage = 24f,
                meterGain = 14f,
                hitStunFrames = 24,
                blockStunFrames = 13,
                pushback = 70f,
                reach = 0f, // Projectile
                heightOffset = 125f,
                hitboxHeight = 45f,
                spawnsProjectile = true,
                soundKey = "projectile"
            )
        ),
        superArt = SpecialMoveDef(
            name = "Shadow Tempest: Izuna Blitz",
            commandHint = "EX / SUPER (100 Meter)",
            description = "Dissolves into five shadow duplicates striking from all angles before slamming down in a lightning vortex!",
            moveData = MoveData(
                name = "Shadow Tempest",
                type = AttackType.SUPER,
                startupFrames = 3,
                activeFrames = 14,
                recoveryFrames = 16,
                damage = 48f,
                meterGain = 0f,
                meterCost = 100f,
                hitStunFrames = 48,
                blockStunFrames = 22,
                pushback = 120f,
                reach = 230f,
                heightOffset = 135f,
                hitboxHeight = 85f,
                isKnockdown = true,
                soundKey = "super_activation"
            )
        ),
        quoteWin = "You fought the shadow... but shadow always wins.",
        quoteLoss = "My speed... was not enough."
    )

    val IGNIS = CharacterDef(
        id = "ignis",
        name = "Ignis",
        subtitle = "CRIMSON DUELIST",
        bio = "A noble master of the flame rapier. Combines elegant fencing footwork with scorching fire arcs to control the neutral space.",
        archetype = Archetype.FLAME_DUELIST,
        fightingStyle = "Fiery rapier fencing & spacing",
        primaryColor = Color(0xFFF97316), // Blazing Flame Orange
        secondaryColor = Color(0xFFEF4444),
        portraitResId = R.drawable.portrait_ignis_1790969339049,
        idleSpriteResId = R.drawable.sprite_ignis_idle_1790970720052,
        attackSpriteResId = R.drawable.sprite_ignis_idle_1790970720052,
        maxHealth = 98f,
        walkSpeed = 350f,
        dashSpeed = 600f,
        jumpVelocity = 720f,
        visualScale = 1.02f,
        lightPunch = MoveData(
            name = "Rapier Thrust",
            type = AttackType.LIGHT_PUNCH,
            startupFrames = 3,
            activeFrames = 3,
            recoveryFrames = 6,
            damage = 8f,
            meterGain = 8f,
            hitStunFrames = 13,
            blockStunFrames = 8,
            pushback = 35f,
            reach = 165f,
            heightOffset = 135f,
            hitboxHeight = 40f,
            soundKey = "slash"
        ),
        heavyPunch = MoveData(
            name = "Crimson Pierce",
            type = AttackType.HEAVY_PUNCH,
            startupFrames = 7,
            activeFrames = 4,
            recoveryFrames = 11,
            damage = 16f,
            meterGain = 15f,
            hitStunFrames = 20,
            blockStunFrames = 12,
            pushback = 75f,
            reach = 210f,
            heightOffset = 130f,
            hitboxHeight = 45f,
            soundKey = "slash"
        ),
        lightKick = MoveData(
            name = "Ember Step",
            type = AttackType.LIGHT_KICK,
            startupFrames = 4,
            activeFrames = 3,
            recoveryFrames = 7,
            damage = 8f,
            meterGain = 9f,
            hitStunFrames = 13,
            blockStunFrames = 8,
            pushback = 35f,
            reach = 150f,
            heightOffset = 50f,
            hitboxHeight = 40f,
            isLow = true,
            soundKey = "hit_light"
        ),
        heavyKick = MoveData(
            name = "Phoenix Arc",
            type = AttackType.HEAVY_KICK,
            startupFrames = 8,
            activeFrames = 5,
            recoveryFrames = 13,
            damage = 19f,
            meterGain = 18f,
            hitStunFrames = 25,
            blockStunFrames = 13,
            pushback = 85f,
            reach = 195f,
            heightOffset = 145f,
            hitboxHeight = 70f,
            isLauncher = true,
            soundKey = "slash"
        ),
        specialMove = SpecialMoveDef(
            name = "Blazing Wheel",
            commandHint = "SP (L / Button)",
            description = "Spins her blade in a flaming circle, unleashing a burning wave of fire across the arena.",
            moveData = MoveData(
                name = "Blazing Wheel",
                type = AttackType.SPECIAL,
                startupFrames = 8,
                activeFrames = 5,
                recoveryFrames = 13,
                damage = 27f,
                meterGain = 15f,
                hitStunFrames = 28,
                blockStunFrames = 15,
                pushback = 85f,
                reach = 0f, // Projectile
                heightOffset = 125f,
                hitboxHeight = 60f,
                spawnsProjectile = true,
                soundKey = "projectile"
            )
        ),
        superArt = SpecialMoveDef(
            name = "Inferno Cross - Phoenix Finale",
            commandHint = "EX / SUPER (100 Meter)",
            description = "Dashes forward at blinding speed, carving a scorching cross of crimson fire that erupts into a phoenix crest!",
            moveData = MoveData(
                name = "Inferno Cross",
                type = AttackType.SUPER,
                startupFrames = 4,
                activeFrames = 13,
                recoveryFrames = 18,
                damage = 52f,
                meterGain = 0f,
                meterCost = 100f,
                hitStunFrames = 46,
                blockStunFrames = 22,
                pushback = 140f,
                reach = 240f,
                heightOffset = 130f,
                hitboxHeight = 90f,
                isKnockdown = true,
                soundKey = "super_activation"
            )
        ),
        quoteWin = "Fencing is an art... and fire is my brush.",
        quoteLoss = "My flame... has flickered out."
    )

    val ALL_FIGHTERS = listOf(KAIRO, COLOSSUS, REN, IGNIS)

    fun getFighter(id: String): CharacterDef {
        return ALL_FIGHTERS.firstOrNull { it.id.equals(id, ignoreCase = true) } ?: KAIRO
    }
}
